Models/AboutMeViewModel.cs
using System.Collections.Generic;

namespace aeh.uber.Models
{
    public class AboutMeViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string PicturePath { get; set; }
        public string Jobtitle { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string Cellphone { get; set; }

        public string CellPhoneLink { get
        {
            return "tel:" + Cellphone.Replace("(0)", "").Replace("-", "").Replace(" ", "").Trim();
        } }

        public string Messenger { get; set; }
        public string LocationDescription { get; set; }
        public string LocationLink { get; set; }
        public string AboutHeading { get; set; }
        public string AboutContent { get; set; }

        public List<ExperienceViewModel> Experiences { get; set; }
        public List<SkillGroupViewModel> SkillGroups { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace aeh.uber.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ExperienceViewModel.cs
using System.Collections.Generic;

namespace aeh.uber.Models
{
    public class ExperienceViewModel
    {
        public int Id { get; set; }
        public string From { get; set; }
        public string Until { get; set; }
        public string Heading { get; set; }
        public string Subheading { get; set; }
        public string Description { get; set; }
        public string KeytopicHeading { get; set; }
        public string TagHeading { get; set; }

        public IList<KeytopicViewModel> Keytopics { get; set; }
        public IList<TagViewModel> Tags { get; set; }


        public string AboutMeId { get; set; }
        public AboutMeViewModel AboutMe { get; set; }


    }
}

Models/KeytopicViewModel.cs
using System.Collections.Generic;

namespace aeh.uber.Models
{
    public class KeytopicViewModel
    {
        public int Id { get; set; }

        public string Description { get; set; }

        public int ExperienceId { get; set; }
        public ExperienceViewModel Experience { get; set; }
    }
}

Models/SkillGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace aeh.uber.Models
{
    public class SkillGroupViewModel
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public bool SkillsContainingLevel { get; set; }


        public List<SkillViewModel> Skills { get; set; }

        public string AboutMeId { get; set; }
        public AboutMeViewModel AboutMe { get; set; }
    }
}

Models/SkillViewModel.cs
using System.Collections.Generic;

namespace aeh.uber.Models
{
    public class SkillViewModel
    {
        public int Id { get; set; }

        public string Description { get; set; }
        public int? Level { get; set; }


        public int SkillGroupId { get; set; }
        public SkillGroupViewModel SkillGroup { get; set; }
    }
}

Models/TagViewModel.cs
using System.Collections.Generic;

namespace aeh.uber.Models
{
    public class TagViewModel
    {
        public int Id { get; set; }

        public string Description { get; set; }

        public int ExperienceId { get; set; }
        public ExperienceViewModel Experience { get; set; }
    }
}

Controllers/CvController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using aeh.uber.Models;
using aeh.uber.Interfaces;
using AutoMapper;

namespace aeh.uber.Controllers
{
    public class CvController : Controller
    {
        private readonly IAppLogic _appLogic;
        private readonly IMapper _mapper;

        public CvController(IAppLogic iAppLogic, IMapper mapper)
        {
            _appLogic = iAppLogic;

            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string id = "aeh")
        {
            var rawData = await _appLogic.GetAboutMeEntryAsync(id);

            if(rawData == null) return NotFound($"Can't find a guy named {id}...");


            var aboutMeViewModel = _mapper.Map<AboutMeViewModel>(rawData);

            return View(aboutMeViewModel);
        }
    }
}

Controllers/HController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using aeh.uber.Models;
using aeh.uber.Interfaces;

namespace aeh.uber.Controllers
{
    public class HController : Controller
    {
        public HController()
        {
        }

        public ActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return Ok();
        }

        public IActionResult Impressum()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Cv/Index.cshtml
@model aeh.uber.Models.AboutMeViewModel
@{
    ViewData["Title"] = "CV - " + Model.Name;
    Layout = "~/Views/Shared/_LayoutCv.cshtml";
}

<header class="resume-header pt-4 pt-md-0">
			    <div class="media flex-column flex-md-row">
				    <img class="mr-3 img-fluid picture mx-auto" src="~/@Model.PicturePath" alt="">
				    <div class="media-body p-4 d-flex flex-column flex-md-row mx-auto mx-lg-0">
					    <div class="primary-info">
						    <h1 class="name mt-0 mb-1 text-white text-uppercase text-uppercase">André Ehlert</h1>
						    <div class="title mb-3">
                                @Model.Jobtitle
                            </div>
						    <ul class="list-unstyled">
							    <li class="mb-2"><a href="mailto:@Model.Email"><i class="far fa-envelope fa-fw mr-2" data-fa-transform="grow-3"></i>@Model.Email</a></li>
							    <li><a href="@Model.CellPhoneLink"><i class="fas fa-mobile-alt fa-fw mr-2" data-fa-transform="grow-6"></i>@Model.Cellphone</a></li>
						    </ul>
					    </div><!--//primary-info-->
					    <div class="secondary-info ml-md-auto mt-2">
						    <ul class="resume-social list-unstyled">
				                <li class="mb-3"><a href="@Model.Web"><span class="fa-container text-center mr-2"><i class="fas fa-globe"></i></span>@Model.Web</a></li>
				                <li class="mb-3"><a href="@Model.Messenger?message"><span class="fa-container text-center mr-2"><i class="fas fa-comment-dots"></i></span>@Model.Messenger</a></li>
				                <li class="mb-3"><a href="@Model.LocationLink" target="_blank" ><span class="fa-container text-center mr-2"><i class="fas fa-map-marked"></i></span>@Model.LocationDescription</a></li>
						    </ul>
					    </div><!--//secondary-info-->
					    
				    </div><!--//media-body-->
			    </div><!--//media-->
		    </header>

            <div class="resume-body p-5">
			    <section class="resume-section summary-section mb-5">
				    <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">@Model.AboutHeading</h2>
				    <div class="resume-section-content">
					    <p class="mb-0">
							@Html.Raw(Model.AboutContent)
						</p>
				    </div>
			    </section><!--//summary-section-->
			    <div class="row">
				    <div class="col-lg-9">
					    <section class="resume-section experience-section mb-5">
						    <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">Erfahrung</h2>
						    <div class="resume-section-content">
							    <div class="resume-timeline position-relative">
                                    @foreach(var experience in @Model.Experiences)
                                    {
                                        <article class="resume-timeline-item position-relative pb-5">

									    <div class="resume-timeline-item-header mb-2">
										    <div class="d-flex flex-column flex-md-row">
										        <h3 class="resume-position-title font-weight-bold mb-1">@experience.Heading</h3>
										        <div class="resume-company-name ml-auto">@experience.Subheading</div>
										    </div><!--//row-->
										    <div class="resume-position-time">
                                                @experience.From 
                                                @experience.Until
                                                </div>
									    </div><!--//resume-timeline-item-header-->

                                        <div class="resume-timeline-item-desc">
										    <p>
                                               @experience.Description 
                                            </p>
											<h4 class="resume-timeline-item-desc-heading font-weight-bold">
                                                @experience.KeytopicHeading
                                            </h4>
										    <ul>
                                                @foreach(var keytopic in experience.Keytopics)
                                                {
                                                    <li>
                                                        @keytopic.Description
                                                    </li>
                                                }
										    </ul>
											<h4 class="resume-timeline-item-desc-heading font-weight-bold">
                                                @experience.TagHeading
                                            </h4>
										    <ul class="list-inline">
                                                 @foreach(var tag in experience.Tags)
                                                {
                                                    <li class="list-inline-item"><span class="badge badge-primary badge-pill">
                                                        @tag.Description
                                                    </span></li>
                                                }
										    </ul>
									    </div><!--//resume-timeline-item-desc-->

								    </article><!--//resume-timeline-item-->
                                        
                                    }
							    </div><!--//resume-timeline-->
						    </div>
					    </section><!--//experience-section-->
				    </div>
				    <div class="col-lg-3">
					    <section class="resume-section skills-section mb-5">
						    <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">Fähigkeiten</h2>
						    <div class="resume-section-content">
                                @foreach(var skillGroup in @Model.SkillGroups.Where(x=> x.Description.StartsWith("<")))
                                {
                                    <div class="resume-skill-item">
							        <h4 class="resume-skills-cat font-weight-bold">
                                        @skillGroup.Description
                                    </h4>
                                        @if(skillGroup.SkillsContainingLevel)
                                        {
                                            <ul class="list-unstyled mb-4">

                                            @foreach(var skill in skillGroup.Skills)
                                            {
                                                <li class="mb-2">
                                                    <div class="resume-skill-name">
                                                        @skill.Description
                                                    </div>
                                                    <div class="progress resume-progress">
                                                        <div class="progress-bar theme-progress-bar-dark" role="progressbar" style="width: @skill.Level%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                                    </div>
                                                </li>
                                            }
                                            </ul>
                                        }
                                        else
                                        {
                                            <ul class="list-inline">

                                            @foreach(var skill in skillGroup.Skills)
                                            {
                                                <li class="list-inline-item"><span class="badge badge-light">@skill.Description</span></li>                                        
                                            }
                                            </ul>
                                        }

						        </div><!--//resume-skill-item-->
                                }

					    </section><!--//interests-section-->

                        
                                @foreach(var skillGroup in @Model.SkillGroups.Where(x=> !x.Description.StartsWith("<")))
                                {
                                   // Sprachen & Interessen...
                                   <section class="resume-section language-section mb-5">

                                   <h2 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">@skillGroup.Description</h2>
                                   <div class="resume-section-content">

                                   @if(skillGroup.Description.ToUpper() == "SPRACHEN")
                                   {
                                            <ul class="list-unstyled resume-lang-list">
                                                @foreach(var skill in skillGroup.Skills)
                                                {
                                                    <li class="mb-2"><span class="resume-lang-name font-weight-bold">@skill.Description</span> <small class="text-muted font-weight-normal"></small></li>
                                                }
                                            </ul>
                                   }
                                   
                                   @if(skillGroup.Description.ToUpper() == "INTERESSEN")
                                   {
                                            <ul class="list-unstyled">
                                                @foreach(var skill in skillGroup.Skills)
                                                {
                                                    <li class="mb-1">@skill.Description</li>
                                                }
                                            </ul>
                                   }
                                   
                                   </div>

                                   </section><!--@skillGroup.Description-sections-->

                                }
						        
					    
				    </div>
			    </div><!--//row-->
		    </div><!--//resume-body-->
		    

Views/H/Impressum.cshtml
@{
    ViewData["Title"] = "Impressum";
    Layout = "~/Views/Shared/_LayoutCv.cshtml";
}
 <div class="resume-body p-5">
<h1 class="resume-section-title text-uppercase font-weight-bold pb-3 mb-3">Impressum</h1>
<h2 class="resume-position-title text-uppercase font-weight-bold pb-2 mb-2">Angaben gem&auml;&szlig; &sect; 5 TMG</h2>
<p>Andr&eacute; Ehlert<br />
Gottlob-Binder-Str. 6<br />
33613 Bielefeld</p>
<h2 class="resume-position-title text-uppercase font-weight-bold pb-2 mb-2">Kontakt</h2>
<p>E-Mail: aeh@posteo.de</p>
<h3 class="resume-position-title text-uppercase font-weight-bold pb-2 mb-2">Haftung f&uuml;r Inhalte</h3> <p>Als Diensteanbieter sind wir gem&auml;&szlig; &sect; 7 Abs.1 TMG
f&uuml;r eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach &sect;&sect; 8 bis 10
TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, &uuml;bermittelte oder gespeicherte fremde
Informationen zu &uuml;berwachen oder nach Umst&auml;nden zu forschen, die auf eine rechtswidrige
T&auml;tigkeit hinweisen.</p> <p>Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen
nach den allgemeinen Gesetzen bleiben hiervon unber&uuml;hrt. Eine diesbez&uuml;gliche Haftung ist jedoch erst
ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung m&ouml;glich. Bei Bekanntwerden von
entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</p> 
<h3 class="resume-position-title text-uppercase font-weight-bold pb-2 mb-2">Haftung f&uuml;r
Links</h3> <p>Unser Angebot enth&auml;lt Links zu externen Websites Dritter, auf deren Inhalte wir keinen
Einfluss haben. Deshalb k&ouml;nnen wir f&uuml;r diese fremden Inhalte auch keine Gew&auml;hr
&uuml;bernehmen. F&uuml;r die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der
Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf m&ouml;gliche
Rechtsverst&ouml;&szlig;e &uuml;berpr&uuml;ft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht
erkennbar.</p> <p>Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete
Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir
derartige Links umgehend entfernen.</p> 
<h3 class="resume-position-title text-uppercase font-weight-bold pb-2 mb-2">Urheberrecht</h3> <p>Die durch die Seitenbetreiber erstellten
Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielf&auml;ltigung,
Bearbeitung, Verbreitung und jede Art der Verwertung au&szlig;erhalb der Grenzen des Urheberrechtes
bed&uuml;rfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser
Seite sind nur f&uuml;r den privaten, nicht kommerziellen Gebrauch gestattet.</p> <p>Soweit die Inhalte auf dieser
Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden
Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam
werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir
derartige Inhalte umgehend entfernen.</p>
<p>Quelle: <a href="https://www.e-recht24.de">eRecht24</a></p>
</div>

Views/H/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - aeh.uber</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cv" asp-action="Index">CV</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="H" asp-action="Impressum">Impressum</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutCv.cshtml
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>@ViewData["Title"]</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	

	<!-- Fonts -->
    <link href="~/roboto-v19-latin/roboto.css" rel="stylesheet" />
    <link href="~/fontawesome/css/all.css" rel="stylesheet" />
       
  
    <!-- Regular CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="~/css/pillar-1.css" />
</head> 

<body>	
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cv" asp-action="Index">CV</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="H" asp-action="Impressum">Impressum</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <article class="resume-wrapper text-center position-relative">
	    <div class="resume-wrapper-inner mx-auto text-left bg-white shadow-lg">
            @RenderBody()
	    </div>
    </article>  


    @RenderSection("Scripts", required: false)    
    <footer class="footer text-center pt-2 pb-5">
	     <!--/* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
                <small class="copyright">Designed with <i class="fas fa-heart"></i> by <a href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    

</body>
</html> 